# filepath: .github/workflows/pr-review.yml
name: PR Review with Codellama

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
  
    permissions:
        contents: write
        pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        ollama serve &
        for i in {1..30}; do
          if curl -s http://localhost:11434 > /dev/null; then
            echo "Ollama server is ready."
            break
          fi
          echo "Waiting for Ollama server to start..."
          sleep 2
        done
        ollama pull codellama || { echo "Failed to pull codellama model"; exit 1; }

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run PR review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
      run: python main.py
